apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
  namespace: umla
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: testwincontainers.azurecr.io/umlaauth
        imagePullPolicy: Always
        env:
        - name: AUTH_PORT
          value: '3000'
        - name: REDIS_URI
          value: redis
        - name: REDIS_PORT
          value: '6379'
        - name: JWT_SECRET
          value: 'mS7HSY5y0qx9SlUufOQn/A=='
        - name: MSG_SENDER_ID
          value: 'WOLUKA'
        - name: MSG_TEMPLATE_ID
          value: '64aea1b0d6fc0531fd0bc303'
        - name: MSG_AUTH_KEY
          value: '400129A8NwNrpkb64a7e5e4P1'
        - name: MONGO_URI
          value: 'mongodb://testwinproddb:GEjpqsis9mmAZB4zbXvThk9s98ElSdxBUIbmiJtVjOdBewX3uWK2e1JGJpsotW3xxImuh3UR6LwVACDbk3eCkQ==@testwinproddb.mongo.cosmos.azure.com:10255/umla?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@testwinproddb@'
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
  - name: auth
    protocol: TCP
    port: 3000
    targetPort: 3000
