export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const ADMIN_LOGOUT = "ADMIN_LOGOUT";

export const GET_USERS_REQUEST = "GET_USERS_REQUEST";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILURE = "GET_USERS_FAILURE";

export const GET_USERS_DATA_REQUEST = "GET_USERS_DATA_REQUEST";
export const GET_USERS_DATA_SUCCESS = "GET_USERS_DATA_SUCCESS";
export const GET_USERS_DATA_FAILURE = "GET_USERS_DATA_FAILURE";

export const DENY_USER_VERIFY_REQUEST = "DENY_USER_VERIFY_REQUEST";
export const DENY_USER_VERIFY_SUCCESS = "DENY_USER_VERIFY_SUCCESS";
export const DENY_USER_VERIFY_FAILURE = "DENY_USER_VERIFY_FAILURE";

export const EARLY_BIRD_USER_REQUEST = "EARLY_BIRD_USER_REQUEST";
export const EARLY_BIRD_USER_SUCCESS = "EARLY_BIRD_USER_SUCCESS";
export const EARLY_BIRD_USER_FAILURE = "EARLY_BIRD_USER_FAILURE";

export const APPROVE_VERIFICATION_REQUEST = "APPROVE_VERIFICATION_REQUEST";
export const APPROVE_VERIFICATION_SUCCESS = "APPROVE_VERIFICATION_SUCCESS";
export const APPROVE_VERIFICATION_FAILURE = "APPROVE_VERIFICATION_FAILURE";

export const SECOND_OFFER_REQUEST = "SECOND_OFFER_REQUEST";
export const SECOND_OFFER_SUCCESS = "SECOND_OFFER_SUCCESS";
export const SECOND_OFFER_FAILURE = "SECOND_OFFER_FAILURE";

export const VERIFY_PROFILE_REQUEST = "VERIFY_PROFILE_REQUEST";
export const VERIFY_PROFILE_SUCCESS = "VERIFY_PROFILE_SUCCESS";
export const VERIFY_PROFILE_FAILURE = "VERIFY_PROFILE_FAILURE";

export const COFFEE_GIVEN_REQUEST = "COFFEE_GIVEN_REQUEST";
export const COFFEE_GIVEN_SUCCESS = "COFFEE_GIVEN_SUCCESS";
export const COFFEE_GIVEN_FAILURE = "COFFEE_GIVEN_FAILURE";

export const BLOCK_USER_REQUEST = "BLOCK_USER_REQUEST";
export const BLOCK_USER_SUCCESS = "BLOCK_USER_SUCCESS";
export const BLOCK_USER_FAILURE = "BLOCK_USER_FAILURE";