export const GET_PARTNER_MEETUP_HISTORY_REQUEST =
  "GET_PARTNER_MEETUP_HISTORY_REQUEST";
export const GET_PARTNER_MEETUP_HISTORY_SUCCESS =
  "GET_PARTNER_MEETUP_HISTORY_SUCCESS";
export const GET_PARTNER_MEETUP_HISTORY_FAILURE =
  "GET_PARTNER_MEETUP_HISTORY_FAILURE";

export const GET_PARTNERS_DATA_REQUEST = "GET_PARTNERS_DATA_REQUEST";
export const GET_PARTNERS_DATA_SUCCESS = "GET_PARTNERS_DATA_SUCCESS";
export const GET_PARTNERS_DATA_FAILURE = "GET_PARTNERS_DATA_FAILURE";

export const GET_PARTNERS_TRANSACTIONS_REQUEST =
  "GET_PARTNERS_TRANSACTIONS_REQUEST";
export const GET_PARTNERS_TRANSACTIONS_SUCCESS =
  "GET_PARTNERS_TRANSACTIONS_SUCCESS";
export const GET_PARTNERS_TRANSACTIONS_FAILURE =
  "GET_PARTNERS_TRANSACTIONS_FAILURE";

export const GET_PARTNER_CITY_DETAILS_REQUEST =
  "GET_PARTNER_CITY_DETAILS_REQUEST";
export const GET_PARTNER_CITY_DETAILS_SUCCESS =
  "GET_PARTNER_CITY_DETAILS_SUCCESS";
export const GET_PARTNER_CITY_DETAILS_FAILURE =
  "GET_PARTNER_CITY_DETAILS_FAILURE";

export const GET_OFFER_CREATION_REQUEST = "GET_OFFER_CREATION_REQUEST";
export const GET_OFFER_CREATION_SUCCESS = "GET_OFFER_CREATION_SUCCESS";
export const GET_OFFER_CREATION_FAILURE = "GET_OFFER_CREATION_FAILURE";

export const GET_MATCHED_REQUEST = "GET_MATCHED_REQUEST";
export const GET_MATCHED_SUCCESS = "GET_MATCHED_SUCCESS";
export const GET_MATCHED_FAILURE = "GET_MATCHED_FAILURE";

export const GET_OFFER_EXPIRED_REQUEST = "GET_OFFER_EXPIRED_REQUEST";
export const GET_OFFER_EXPIRED_SUCCESS = "GET_OFFER_EXPIRED_SUCCESS";
export const GET_OFFER_EXPIRED_FAILURE = "GET_OFFER_EXPIRED_FAILURE";

export const GET_CREDIT_AMOUNT_REQUEST = "GET_CREDIT_AMOUNT_REQUEST";
export const GET_CREDIT_AMOUNT_SUCCESS = "GET_CREDIT_AMOUNT_SUCCESS";
export const GET_CREDIT_AMOUNT_FAILURE = "GET_CREDIT_AMOUNT_FAILURE";

export const GET_DEBIT_AMOUNT_REQUEST = "GET_DEBIT_AMOUNT_REQUEST";
export const GET_DEBIT_AMOUNT_SUCCESS = "GET_DEBIT_AMOUNT_SUCCESS";
export const GET_DEBIT_AMOUNT_FAILURE = "GET_DEBIT_AMOUNT_FAILURE";

export const GET_USER_QUERY_REQUEST = "GET_USER_QUERY_REQUEST";
export const GET_USER_QUERY_SUCCESS = "GET_USER_QUERY_SUCCESS";
export const GET_USER_QUERY_FAILURE = "GET_USER_QUERY_FAILURE";

export const ADD_QUERY_REPLY_REQUEST = "ADD_QUERY_REPLY_REQUEST";
export const ADD_QUERY_REPLY_SUCCESS = "ADD_QUERY_REPLY_SUCCESS";
export const ADD_QUERY_REPLY_FAILURE = "ADD_QUERY_REPLY_FAILURE";

export const GET_REFUND_REQUEST = "GET_REFUND_REQUEST";
export const GET_REFUND_SUCCESS = "GET_REFUND_SUCCESS";
export const GET_REFUND_FAILURE = "GET_REFUND_FAILURE";

export const GET_RESTAURANTS_REQUEST = "GET_RESTAURANTS_REQUEST";
export const GET_RESTAURANTS_SUCCESS = "GET_RESTAURANTS_SUCCESS";
export const GET_RESTAURANTS_FAILURE = "GET_RESTAURANTS_FAILURE";

export const GET_MENU_ITEMS_REQUEST = "GET_MENU_ITEMS_REQUEST";
export const GET_MENU_ITEMS_SUCCESS = "GET_MENU_ITEMS_SUCCESS";
export const GET_MENU_ITEMS_FAILURE = "GET_MENU_ITEMS_FAILURE";

export const CLAIM_OFFER_SUBMIT_REQUEST = "CLAIM_OFFER_SUBMIT_REQUEST";
export const CLAIM_OFFER_SUBMIT_SUCCESS = "CLAIM_OFFER_SUBMIT_SUCCESS";
export const CLAIM_OFFER_SUBMIT_FAILURE = "CLAIM_OFFER_SUBMIT_FAILURE";

export const GET_PARTNER_DETAILS_REQUEST = "GET_PARTNER_DETAILS_REQUEST";
export const GET_PARTNER_DETAILS_SUCCESS = "GET_PARTNER_DETAILS_SUCCESS";
export const GET_PARTNER_DETAILS_FAILURE = "GET_PARTNER_DETAILS_FAILURE";

export const GET_PARTNER_MENU_REQUEST = "GET_PARTNER_MENU_REQUEST";
export const GET_PARTNER_MENU_SUCCESS = "GET_PARTNER_MENU_SUCCESS";
export const GET_PARTNER_MENU_FAILURE = "GET_PARTNER_MENU_FAILURE";

export const GET_USER_ALERT_REQUEST = "GET_USER_ALERT_REQUEST";
export const GET_USER_ALERT_SUCCESS = "GET_USER_ALERT_SUCCESS";
export const GET_USER_ALERT_FAILURE = "GET_USER_ALERT_FAILURE";

export const GET_USER_REPORT_REQUEST = "GET_USER_REPORT_REQUEST";
export const GET_USER_REPORT_SUCCESS = "GET_USER_REPORT_SUCCESS";
export const GET_USER_REPORT_FAILURE = "GET_USER_REPORT_FAILURE";

export const GET_FLOATING_OFFERS_REQUEST = "GET_FLOATING_OFFERS_REQUEST";
export const GET_FLOATING_OFFERS_SUCCESS = "GET_FLOATING_OFFERS_SUCCESS";
export const GET_FLOATING_OFFERS_FAILURE = "GET_FLOATING_OFFERS_FAILURE";

export const GET_USER_OFFERS_REQUEST = "GET_USER_OFFERS_REQUEST";
export const GET_USER_OFFERS_SUCCESS = "GET_USER_OFFERS_SUCCESS";
export const GET_USER_OFFERS_FAILURE = "GET_USER_OFFERS_FAILURE";

export const GET_USER_FEEDBACKS_REQUEST = "GET_USER_FEEDBACKS_REQUEST";
export const GET_USER_FEEDBACKS_SUCCESS = "GET_USER_FEEDBACKS_SUCCESS";
export const GET_USER_FEEDBACKS_FAILURE = "GET_USER_FEEDBACKS_FAILURE";

export const GET_DASHBOARD_UPPER_FIGURES_REQUEST = "GET_DASHBOARD_UPPER_FIGURES_REQUEST";
export const GET_DASHBOARD_UPPER_FIGURES_SUCCESS = "GET_DASHBOARD_UPPER_FIGURES_SUCCESS";
export const GET_DASHBOARD_UPPER_FIGURES_FAILURE = "GET_DASHBOARD_UPPER_FIGURES_FAILURE";

export const GET_DASHBOARD_NEW_USERS_REQUEST = "GET_DASHBOARD_NEW_USERS_REQUEST";
export const GET_DASHBOARD_NEW_USERS_SUCCESS = "GET_DASHBOARD_NEW_USERS_SUCCESS";
export const GET_DASHBOARD_NEW_USERS_FAILURE = "GET_DASHBOARD_NEW_USERS_FAILURE";

export const GET_DASHBOARD_NEW_REPORTS_REQUEST = "GET_DASHBOARD_NEW_REPORTS_REQUEST";
export const GET_DASHBOARD_NEW_REPORTS_SUCCESS = "GET_DASHBOARD_NEW_REPORTS_SUCCESS";
export const GET_DASHBOARD_NEW_REPORTS_FAILURE = "GET_DASHBOARD_NEW_REPORTS_FAILURE";

export const GET_DASHBOARD_NEW_MATCH_REQUEST = "GET_DASHBOARD_NEW_MATCH_REQUEST";
export const GET_DASHBOARD_NEW_MATCH_SUCCESS = "GET_DASHBOARD_NEW_MATCH_SUCCESS";
export const GET_DASHBOARD_NEW_MATCH_FAILURE = "GET_DASHBOARD_NEW_MATCH_FAILURE";

export const GET_DASHBOARD_OFFERING_ITEMS_REQUEST = "GET_DASHBOARD_OFFERING_ITEMS_REQUEST";
export const GET_DASHBOARD_OFFERING_ITEMS_SUCCESS = "GET_DASHBOARD_OFFERING_ITEMS_SUCCESS";
export const GET_DASHBOARD_OFFERING_ITEMS_FAILURE = "GET_DASHBOARD_OFFERING_ITEMS_FAILURE";

export const GET_DASHBOARD_ALERTS_REQUEST = "GET_DASHBOARD_ALERTS_REQUEST";
export const GET_DASHBOARD_ALERTS_SUCCESS = "GET_DASHBOARD_ALERTS_SUCCESS";
export const GET_DASHBOARD_ALERTS_FAILURE = "GET_DASHBOARD_ALERTS_FAILURE";

export const GET_DASHBOARD_REVENUE_REQUEST = "GET_DASHBOARD_REVENUE_REQUEST";
export const GET_DASHBOARD_REVENUE_SUCCESS = "GET_DASHBOARD_REVENUE_SUCCESS";
export const GET_DASHBOARD_REVENUE_FAILURE = "GET_DASHBOARD_REVENUE_FAILURE";

export const GET_DASHBOARD_TRAFFIC_REQUEST = "GET_DASHBOARD_TRAFFIC_REQUEST";
export const GET_DASHBOARD_TRAFFIC_SUCCESS = "GET_DASHBOARD_TRAFFIC_SUCCESS";
export const GET_DASHBOARD_TRAFFIC_FAILURE = "GET_DASHBOARD_TRAFFIC_FAILURE";