export const GET_ALL_USERS_REQUEST = "GET_ALL_USERS_REQUEST";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAILURE = "GET_ALL_USERS_FAILURE";

export const GET_USER_PROFILE_REQUEST = "GET_USER_PROFILE_REQUEST";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_FAILURE = "GET_USER_PROFILE_FAILURE";

export const GET_BOOKINGS_REQUEST = "GET_BOOKINGS_REQUEST";
export const GET_BOOKINGS_SUCCESS = "GET_BOOKINGS_SUCCESS";
export const GET_BOOKINGS_FAILURE = "GET_BOOKINGS_FAILURE";

export const GET_OUTLETS_REQUEST = "GET_OUTLETS_REQUEST";
export const GET_OUTLETS_SUCCESS = "GET_OUTLETS_SUCCESS";
export const GET_OUTLETS_FAILURE = "GET_OUTLETS_FAILURE";

export const GET_OUTLET_CITY_REQUEST = "GET_OUTLET_CITY_REQUEST";
export const GET_OUTLET_CITY_SUCCESS = "GET_OUTLET_CITY_SUCCESS";
export const GET_OUTLET_CITY_FAILURE = "GET_OUTLET_CITY_FAILURE";

export const GET_WEEKLY_BOOKINGS_REQUEST = "GET_WEEKLY_BOOKINGS_REQUEST";
export const GET_WEEKLY_BOOKINGS_SUCCESS = "GET_WEEKLY_BOOKINGS_SUCCESS";
export const GET_WEEKLY_BOOKINGS_FAILURE = "GET_WEEKLY_BOOKINGS_FAILURE";

export const GET_USER_TRAFFIC_REQUEST = "GET_USER_TRAFFIC_REQUEST";
export const GET_USER_TRAFFIC_SUCCESS = "GET_USER_TRAFFIC_SUCCESS";
export const GET_USER_TRAFFIC_FAILURE = "GET_USER_TRAFFIC_FAILURE";

export const GET_USER_PURCHASES_REQUEST = "GET_USER_PURCHASES_REQUEST";
export const GET_USER_PURCHASES_SUCCESS = "GET_USER_PURCHASES_SUCCESS";
export const GET_USER_PURCHASES_FAILURE = "GET_USER_PURCHASES_FAILURE";

export const GET_USER_MEETUPS_REQUEST = "GET_USER_MEETUPS_REQUEST";
export const GET_USER_MEETUPS_SUCCESS = "GET_USER_MEETUPS_SUCCESS";
export const GET_USER_MEETUPS_FAILURE = "GET_USER_MEETUPS_FAILURE";

export const GET_USER_MATCHES_REQUEST = "GET_USER_MATCHES_REQUEST";
export const GET_USER_MATCHES_SUCCESS = "GET_USER_MATCHES_SUCCESS";
export const GET_USER_MATCHES_FAILURE = "GET_USER_MATCHES_FAILURE";

export const GET_USER_DEALS_REQUEST = "GET_USER_DEALS_REQUEST";
export const GET_USER_DEALS_SUCCESS = "GET_USER_DEALS_SUCCESS";
export const GET_USER_DEALS_FAILURE = "GET_USER_DEALS_FAILURE";

export const GET_VERIFIED_USERS_REQUEST = "GET_VERIFIED_USERS_REQUEST";
export const GET_VERIFIED_USERS_SUCCESS = "GET_VERIFIED_USERS_SUCCESS";
export const GET_VERIFIED_USERS_FAILURE = "GET_VERIFIED_USERS_FAILURE";

export const GET_UNVERIFIED_USERS_REQUEST = "GET_UNVERIFIED_USERS_REQUEST";
export const GET_UNVERIFIED_USERS_SUCCESS = "GET_UNVERIFIED_USERS_SUCCESS";
export const GET_UNVERIFIED_USERS_FAILURE = "GET_UNVERIFIED_USERS_FAILURE";

export const GET_USER_DATA_MEETUP_REQUEST = "GET_USER_DATA_MEETUP_REQUEST";
export const GET_USER_DATA_MEETUP_SUCCESS = "GET_USER_DATA_MEETUP_SUCCESS";
export const GET_USER_DATA_MEETUP_FAILURE = "GET_USER_DATA_MEETUP_FAILURE";