apiVersion: apps/v1
kind: Deployment
metadata:
  name: offer-depl
  namespace: umla
spec:
  replicas: 1
  selector:
    matchLabels:
      app: offer
  template:
    metadata:
      labels:
        app: offer
    spec:
      containers:
      - name: offer
        image: testwincontainers.azurecr.io/umlaoffer
        imagePullPolicy: Always
        env:
        - name: AUTH_PORT
          value: '3000'
        - name: OFFER_PORT
          value: '3007'
        - name: SWIPE_PORT
          value: '3002'
        - name: REDIS_URI
          value: redis
        - name: REDIS_PORT
          value: '6379'
        - name: JWT_SECRET
          value: 'mS7HSY5y0qx9SlUufOQn/A=='
        - name: AUTH_SERVICE
          value: 'http://auth-srv:3000'
        - name: MSG_SENDER_ID
          value: 'WOLUKA'
        - name: MSG_TEMPLATE_ID
          value: '64aea1b0d6fc0531fd0bc303'
        - name: MSG_AUTH_KEY
          value: '400129A8NwNrpkb64a7e5e4P1'
        - name: MONGO_URI
          value: 'mongodb://testwinproddb:GEjpqsis9mmAZB4zbXvThk9s98ElSdxBUIbmiJtVjOdBewX3uWK2e1JGJpsotW3xxImuh3UR6LwVACDbk3eCkQ==@testwinproddb.mongo.cosmos.azure.com:10255/umla?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@testwinproddb@'
        - name: FIREBASE_KEY
          value: "AAAAmWi6wHU:APA91bFUyQgZv_B1gdhPvpaMV3TSbErwur1XyjPXWoaEar0fSAVoJWJcO2Yg5p_8Z-c7XYP1k_uX7yTfLJZ9aL6uWdR9s4f0ghRujuRntcaY06sOGpP--mA-mHlzlBZ0eHn1zPOV8RPX"
        - name: PARTNER_DASHBOARD_SERVICE
          value: "http://partnerdashboard-srv:3010"
        - name: OFFER_SERVICE
          value: "http://offer-srv:3007"
---
apiVersion: v1
kind: Service
metadata:
  name: offer-srv
spec:
  selector:
    app: offer
  ports:
  - name: offer
    protocol: TCP
    port: 3007
    targetPort: 3007
